### ISSUE TITLE
Утвердить названия в колесе плутчика

### ISSUE THREAD

**Issue by kmvpvl** [kmvpvl/EmotionalAzimuth#1]
И для русского и для английского вариантов нужно утвердить названия

**Comment by Komo-Pet** [comment]
Ecstasy – экстаз
joy – радость
serenity – безмятежность

admiration – восхищение (как высшая степень доверия, верность)
trust – доверие
acceptance – принятие

terror – ужас
fear – страх
apprehension – тревога

amazement – изумление
surprise – удивление
distraction – растерянность

grief – горе
sadness – печаль
pensiveness – грусть 

loathing – ненависть (возможно выглядит как злость, поэтому есть второй вариант), мерзость
disgust – отвращение
boredom – скука

rage – ярость
anger – злость
annoyance – раздражение

vigiliance – настороженность
anticipation – ожидание
interest – интерес
