### ISSUE TITLE
Надо ли убирать для обычных пользователей тумблер on/off

### ISSUE THREAD

**Issue by Komo-Pet** [kmvpvl/EmotionalAzimuth#19]
Мне кажется для них неактуально включать лексему в список или нет, так как лексемы решаются по мере поступления плюс есть возможность вернуться к оценённым лексемам с помощью тумблера evaluated/not

Возможно я не понимаю, как работает on/off.

**Comment by kmvpvl** [comment]
может его устанавливать в он по умолчанию?
