### ISSUE TITLE
Полностью оценить все лексемы из бунина

### ISSUE THREAD

**Issue by kmvpvl** [kmvpvl/EmotionalAzimuth#6]

**Comment by Komo-Pet** [comment]
все лексемы были оценены за 40 минут, количество не считал.

из замечаний:
1) программа давала несуществующие слова ("нея", "мень"), были помечены как ignore.
2) программа давала некорректные инфинитивы ("причесывалисяться" или что-то про причесывание), были помечены, как ignore
3) программа выдавала некорректные формы прилагательных ("любящий жена"), было помечено как include и оценено.
4) программа выдавала словосочетания, которые невозможно употребить в обычной речи, следовательно невозможно оценить эмоциональный отклик ("заголившейся волос", заголить можно часть тела без сильного волосяного покрова, но не волос), были помечены как ignore.
5) при оценке лексемы после нажатия кнопки "save" лексема не исчезала из списка, проблема решалась с помощью оценки следующей лексемы.
